NTH_231220800_lab06/Models/Learner.cs
namespace Day_12_lab1.Models
{
    public class Learner
    {
        public Learner()
        {
            Enrollment = new HashSet<Enrollment>();
        }
        public int LearnerID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }
        public DateTime EnrollmentDate { get; set; }
        public int MajorID { get; set; }
        public virtual Major? Major { get; set; }
        public virtual ICollection<Enrollment> Enrollment { get; set; }
    }
}

NTH_231220800_lab06/Controllers/LearnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Day_12_lab1.Models;

namespace Day_12_lab1.Controllers
{
    public class LearnersController : Controller
    {
        private readonly SchoolContext _context;

        public LearnersController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Learners
        private int pageSize = 1;
        public async Task<IActionResult> Index(int? mid)
        {
            IQueryable<Learner> learnersQuery = _context.Learners.Include(l => l.Major);

            if (mid != null)
            {
                learnersQuery = (IQueryable<Learner>)_context.Learners
                    .Where(l => l.MajorID == mid)
                    .Include(m => m.Major);
            }

            int pageNum = (int)Math.Ceiling(learnersQuery.Count() / (float)pageSize);
            ViewBag.pageNum = pageNum;
            var learners = await learnersQuery.ToListAsync();

            // gọi AJAX
            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_LearnerTable", learners);
            }

            return View(learners);
        }
        public async Task<IActionResult> LearnerFilter(int? mid, string? keyword, int? pageIndex)
        {
            var learners = (IQueryable<Learner>)_context.Learners;

            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);
            if (mid != null)
            {
                learners = learners.Where(l => l.MajorID == mid);
                ViewBag.mid = mid;
            }

            if (keyword != null)
            {
                learners = learners.Where(l => l.FirstMidName.ToLower().Contains(keyword.ToLower()));
                ViewBag.keyword = keyword;
            }
            int pageNum = (int)Math.Ceiling(learners.Count() / (float)pageSize);
            ViewBag.pageNum = pageNum;
            var result = learners.Skip(pageSize * (page - 1)).Take(pageSize).Include(m => m.Major);
            return PartialView("_LearnerTable", result);
        }

        // GET: Learners/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners
                .Include(l => l.Major)
                .FirstOrDefaultAsync(m => m.LearnerID == id);
            if (learner == null)
            {
                return NotFound();
            }

            return View(learner);
        }

        // GET: Learners/Create
        public IActionResult Create()
        {
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID");
            return View();
        }

        // POST: Learners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LearnerID,LastName,FirstMidName,EnrollmentDate,MajorID")] Learner learner)
        {
            if (ModelState.IsValid)
            {
                _context.Add(learner);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // GET: Learners/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners.FindAsync(id);
            if (learner == null)
            {
                return NotFound();
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // POST: Learners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LearnerID,LastName,FirstMidName,EnrollmentDate,MajorID")] Learner learner)
        {
            if (id != learner.LearnerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(learner);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LearnerExists(learner.LearnerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MajorID"] = new SelectList(_context.Majors, "MajorID", "MajorID", learner.MajorID);
            return View(learner);
        }

        // GET: Learners/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learner = await _context.Learners
                .Include(l => l.Major)
                .FirstOrDefaultAsync(m => m.LearnerID == id);
            if (learner == null)
            {
                return NotFound();
            }

            return View(learner);
        }

        // POST: Learners/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var learner = await _context.Learners.FindAsync(id);
            if (learner != null)
            {
                _context.Learners.Remove(learner);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LearnerExists(int id)
        {
            return _context.Learners.Any(e => e.LearnerID == id);
        }
    }
}

NTH_231220800_lab06/Controllers/StudentController.cs
using Day_12_lab1.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Day_12_lab1.Controllers
{
    [Route("Admin/Student")]
    public class StudentController : Controller
    {
        private static List<Student> students;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public StudentController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            if (students == null)
            {
                students = new List<Student>()
                {
                    new Student { Id = 1, Name = "Nguyen Van A", Email = "a@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Male, IsRegular=true, Address="Ha Noi", DateOfBorth=new DateTime(2003,5,12) },
                    new Student { Id = 2, Name = "Tran Thi B", Email = "b@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=false, Address="Hai Phong", DateOfBorth=new DateTime(2004,1,22) },
                    new Student { Id = 3, Name = "Le Van C", Email = "c@example.com", Password="123", Branch = Branch.IT, Gender = Gender.Male, IsRegular=true, Address="Da Nang", DateOfBorth=new DateTime(2002,11,3) },
                    new Student { Id = 4, Name = "Pham Thi D", Email = "d@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="HCMC", DateOfBorth=new DateTime(2003,4,9) },
                    new Student { Id = 5, Name = "Hoang Van E", Email = "e@example.com", Password="123", Branch = Branch.EE, Gender = Gender.Male, IsRegular=false, Address="Hue", DateOfBorth=new DateTime(2001,2,15) },
                    new Student { Id = 6, Name = "Nguyen Thi F", Email = "f@example.com", Password="123", Branch = Branch.BE, Gender = Gender.Female, IsRegular=true, Address="Can Tho", DateOfBorth=new DateTime(2003,9,30) },
                    new Student { Id = 7, Name = "Bui Van G", Email = "g@example.com", Password="123", Branch = Branch.EE, Gender = Gender.Male, IsRegular=true, Address="Ninh Binh", DateOfBorth=new DateTime(2002,6,17) },
                    new Student { Id = 8, Name = "Vo Thi H", Email = "h@example.com", Password="123", Branch = Branch.IT, Gender = Gender.Female, IsRegular=false, Address="Quang Ninh", DateOfBorth=new DateTime(2004,7,2) },
                    new Student { Id = 9, Name = "Dang Van I", Email = "i@example.com", Password="123", Branch = Branch.IT, Gender = Gender.Male, IsRegular=true, Address="Ha Tinh", DateOfBorth=new DateTime(2003,8,21) },
                    new Student { Id = 10, Name = "Truong Thi J", Email = "j@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="Ben Tre", DateOfBorth=new DateTime(2004,12,10) },
                    new Student { Id = 11, Name = "Nguyen Van K", Email = "k@example.com", Password="123", Branch = Branch.EE, Gender = Gender.Male, IsRegular=false, Address="Ha Noi", DateOfBorth=new DateTime(2002,3,5) },
                    new Student { Id = 12, Name = "Le Thi L", Email = "l@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="Lang Son", DateOfBorth=new DateTime(2003,10,14) },
                    new Student { Id = 13, Name = "Pham Van M", Email = "m@example.com", Password="123", Branch = Branch.BE, Gender = Gender.Male, IsRegular=true, Address="Nam Dinh", DateOfBorth=new DateTime(2001,1,19) },
                    new Student { Id = 14, Name = "Hoang Thi N", Email = "n@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="Thanh Hoa", DateOfBorth=new DateTime(2004,4,4) },
                    new Student { Id = 15, Name = "Do Van O", Email = "o@example.com", Password="123", Branch = Branch.IT, Gender = Gender.Male, IsRegular=false, Address="HCMC", DateOfBorth=new DateTime(2002,9,27) },
                    new Student { Id = 16, Name = "Vu Thi P", Email = "p@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="Ha Giang", DateOfBorth=new DateTime(2003,11,8) },
                    new Student { Id = 17, Name = "Ngo Van Q", Email = "q@example.com", Password="123", Branch = Branch.BE, Gender = Gender.Male, IsRegular=true, Address="Tay Ninh", DateOfBorth=new DateTime(2001,6,6) },
                    new Student { Id = 18, Name = "Trinh Thi R", Email = "r@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=false, Address="Vinh Long", DateOfBorth=new DateTime(2002,12,25) },
                    new Student { Id = 19, Name = "Mai Van S", Email = "s@example.com", Password="123", Branch = Branch.EE, Gender = Gender.Male, IsRegular=true, Address="Khanh Hoa", DateOfBorth=new DateTime(2003,3,12) },
                    new Student { Id = 20, Name = "Ngo Thi T", Email = "t@example.com", Password="123", Branch = Branch.CE, Gender = Gender.Female, IsRegular=true, Address="Phu Tho", DateOfBorth=new DateTime(2004,5,29) },
                };
            }
        }

        [Route("List")]
        public async Task<IActionResult> Index()
        {
            Console.WriteLine(">>> [GET] Đang tải Index. Tổng số SV: " + students.Count);
            return View(students);
        }

        [HttpGet]
        [Route("Add")]
        public async Task<IActionResult> Create()
        {
            ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
            ViewBag.AllBranch = new List<SelectListItem>()
            {
                new SelectListItem { Text = "IT", Value = "1" },
                new SelectListItem { Text = "BE", Value = "2" },
                new SelectListItem { Text = "CE", Value = "3" },
                new SelectListItem { Text = "EE", Value = "4" }
            };
            return View();
        }

        [HttpPost]
        [Route("Add")]
        public async Task<IActionResult> Create(Student s)
        {
            if (ModelState.IsValid)
            {
                s.Id = students.Last<Student>().Id + 1;
                students.Add(s);
                return RedirectToAction("Index", students);
            }

            ViewBag.AllGenders = Enum.GetValues(typeof(Gender)).Cast<Gender>().ToList();
            ViewBag.AllBranch = new List<SelectListItem>()
                {
                    new SelectListItem { Text = "IT", Value = "1" },
                    new SelectListItem { Text = "BE", Value = "2" },
                    new SelectListItem { Text = "CE", Value = "3" },
                    new SelectListItem { Text = "EE", Value = "4" }
                };

            if (s.ProfileImage != null)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string uploadPath = Path.Combine(wwwRootPath, "images", "students");
                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                    Console.WriteLine("${uploadPath}");
                }
                string uniqueFileName = Guid.NewGuid().ToString() + "_" + s.ProfileImage.FileName;
                string filePath = Path.Combine(uploadPath, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await s.ProfileImage.CopyToAsync(fileStream);
                }
                s.ProfileImagePath = "/images/students/" + uniqueFileName;
            }
            Console.WriteLine(">>> [POST] Đã thêm. Tổng số SV: " + students.Count);
            return View();
        }
    }
}

NTH_231220800_lab06/ViewComponents/MajorViewComponent.cs
using Day_12_lab1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Day_12_lab1.ViewComponents
{
    public class MajorViewComponent : ViewComponent
    {
        SchoolContext db;
        List<Major> majors;
        public MajorViewComponent(SchoolContext context)
        {
            db = context;
            majors = db.Majors.ToList();
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Views/Shared/_MajorViewComponent.cshtml", majors);
        }
    }
}

NTH_231220800_lab06/ViewComponents/RenderViewComponent.cs
using Day_12_lab1.Models;
using Microsoft.AspNetCore.Mvc;

namespace Day_12_lab1.ViewComponents
{
    public class RenderViewComponent : ViewComponent
    {
        private readonly List<MenuItem> menuItems;

        public RenderViewComponent()
        {
            menuItems = new List<MenuItem>()
            {
                new MenuItem() {Id=1, Name="List Student", Link="/Admin/Student/list" },
                new MenuItem() {Id=2, Name="Add Student", Link="/Admin/Student/add" },
                new MenuItem() {Id=3, Name="List Learners", Link="/Learners/Index" },
                new MenuItem() {Id=4, Name="Add Student", Link="/Learners/Create" },

            };
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("~/Views/Shared/_leftMenu.cshtml", menuItems);
        }
    }
}

NTH_231220800_lab06/Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <partial name="_topNav"/>
    <div id="layoutSidenav">
        @* <partial name="_leftMenu"/> *@
        @await Component.InvokeAsync("Render");
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <partial name="_Footer"/>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/js/datatables-simple-demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NTH_231220800_lab06/Views/Shared/_Footer.cshtml
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; Your Website 2023</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

NTH_231220800_lab06/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Day_12_lab1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Day_12_lab1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Day_12_lab1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Create">Add</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Day_12_lab1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NTH_231220800_lab06/Views/Shared/_LearnerTable.cshtml
@model IEnumerable<Learner>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstMidName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EnrollmentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Major)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstMidName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EnrollmentDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Major.MajorID)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.LearnerID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.LearnerID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.LearnerID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<ul class="pagination">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item" page="@i">
            @(ViewBag.mid != null ? "mid=" + ViewBag.mid : "")
            @(ViewBag.Keyword != null ? " keyword=" + ViewBag.Keyword : "")
            <a class="page-link">@i</a>
        </li>
    }
</ul>

NTH_231220800_lab06/Views/Shared/_MajorViewComponent.cshtml
@model IEnumerable<Major>

<ul class="nav">
    @foreach (var major in Model)
    {
        <li class="nav-item" id="@major.MajorID">
            <a class="nav-link">
                @major.MajorName
            </a>
        </li>
    }
</ul>

NTH_231220800_lab06/Views/Shared/_leftMenu.cshtml
@model IEnumerable<MenuItem>

<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="index.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Layouts
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="layout-static.html">Static Navigation</a>
                        <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Pages
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                            Error
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                @foreach (var m in Model)
                {
                    <a class="nav-link" href="@m.Link">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        @m.Name
                    </a>
                }
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            Start Bootstrap
        </div>
    </nav>
</div>

NTH_231220800_lab06/Views/Shared/_topNav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="index.html">Start Bootstrap</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

          